apiVersion: v1
kind: Service
metadata:
  name: scheduler-extender-service
  namespace: kube-system
spec:
  selector:
    name: scheduler-extender-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 12345
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-extender-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scheduler-extender-deploy
  template:
    metadata:
      labels:
        name: scheduler-extender-deploy
    spec:
      containers:
      - image: coldtea214/scheduler-extender:1.0
        name: scheduler-extender
